6 UI architecture
AleksVira/AcademyFundamentalsProject pull request #3
Opened 2021-01-09 17:48 UTC by AleksVira

Текущее состояние домашки, включая 6-е задание

2021-01-10 01:16 UTC, Vladuken requested changes
Проверил!

В целом структурно все ок, большая часть комментариев относятся к деталям, которые дальше класса где прокомментировал даже и не пойдут.

Думал будет побольше комментов)


Из мелких штук которые встречаются повсеместно:

В ConstraintLayout лучше ширину и высоту указывать 0dp и просто правильно расставлять констрейнты
Также можно в xml не использовать AppCompat***, а просто указывать названия вьюх
Также пройдись по цветам, и подбирай дублирование внутри всяких drawable и прочего, где можно это вынести. 

По коду (который на Kotlin) в основном все в комментариях указано.

Можешь прочитать все комменты подробно, и если хочешь ,можем завтра созвониться, если будут вопросы

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/MainActivity.kt
> +*/
Думаю такие комментарии для чистоты кода можно удалить, если что, потом просто поменяешь onMovieCardSelected

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/data/ActorData.kt
> +@Parcelize
В классах ActorData, GenreData и MovieData можно сейчас убрать @Parcelize и Parcelable, потому что сейчас это нигде не используется , а так модельку можно сделать более "чистой", с меньшим количеством зависимостей.

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/data/ActorData.kt
> +@Parcelize
Ну и еще чисто субъективное - я бы назвал не  ActorData, GenreData и MovieData , а Actor, Genre и Movie

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/data/ActorData.kt
> +    val imageUrl: String = ""
И еще - мне кажется здесь лучше убрать значения по умолчанию а оставить бы просто:

```
data class ActorData(
    val id: Int,
    val name: String,
    val imageUrl: String
) 
```

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/data/GenreData.kt
> +) : Parcelable
Точно так-же:
Убрать Parcelize и Parcelable

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/data/MovieData.kt
> +) : Parcelable
Здесь тоже:

Убрать Parcelable  и @Parcelize 
и Убрать значения по умолчанию

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/data/MovieMockedData.kt
> +package com.example.academyfundamentalsproject.data
Этот файл никак не используется, поэтому его можно удалить

(Либо я иногда еще у себя делаю так: если думаю что он вдруг еще понадобится когда-нибудь, то его можно поменять какой нибудь аннотацией типо `@Deprecated `или еще как-нибудь (знаю что она для другого предназначена, но в итоге в Android Studio оно выглядит красиво))
Вот так:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/23121846/104105865-59e14280-52c2-11eb-99ea-212b362cb5d9.png">


Короче можешь удалить, или пометить для себя что он не используется  (я бы это удалил, но тут тебе решать)

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +    private var movieCardClickListener: MovieCardClickListener? = null
Вообще я думаю что здесь можно сделать 
`private lateinit var movieCardClickListener: MovieCardClickListener`

Так мы избавимся от nullability, но да, если вдруг контекст не будет реализовывать `MovieCardClickListener`, то тогда приложение будет падать с NotInitializedException (что кстати можно рассматривать как плюс, потому что падать будет только если мы забыли у Activity реализовать этот интерфейс)

Опять же я не говорю что это значит что нельзя делать 
`private var movieCardClickListener: MovieCardClickListener? = null`
Но мне кажется именно в этом случае можно избавиться от nullability

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +    private lateinit var recycler: RecyclerView
Здесь я думаю что можно убрать тоже переменную для хранения ссылки на recyclerView из полей фрагмента, а просто использовать binding объект напрямую

Так код фрагмента станет чище

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +    private lateinit var mainListAdapter: MainListAdapter
Адаптер можно сразу здесь создать, а не внутри initView() 

Плюс для удобства читания можно лямбды проименовать(вот так это будет выглядеть ):

 
   ```
 private val mainListAdapter: MainListAdapter = MainListAdapter(
        movieCardClickListener = { adapterIndex ->
            moviesViewModel.select(adapterIndex)
            movieCardClickListener.onMovieCardSelected()
        },
        onFavoriteClick = { adapterIndex, _ ->
            moviesViewModel.changeFavouriteState(adapterIndex)
        })
```

Но вообще да, потом доберемся еще до адаптера, его я бы тоже отрефакторил, так что то что выше это пока промежуточный вариант, но суть в том что его можно проиниализмровать и сделать val и также проименовать параметры чтобы понятнее было читать

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +    private val binding get() = _binding!!
А вот здесь можно избавиться от nullability вот так:
`  private lateinit var binding: FragmentMoviesListBinding`
и 

```
  override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?,
    ): View {
        binding = FragmentMoviesListBinding.inflate(inflater, container, false)
        return binding.root
    }

```


Приватная переменная тогда уберется и можно будет не присваивать null в onDetach
(на официальном сайте с документацией тоже уже поменяли на такой подход как я описал, а раньше там было то что есть сейчас в коде у тебя)

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +        binding.moviesListHeader.text = getString(R.string.movies_list)
вот это ты можешь просто поставить параметр в xml  
`android:text="@string/movies_list"`

и тебе не нужно будет в коде делать это (учитывая что это не изменяемая строка, ее можно без проблем запихнуть в xml)

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +        recycler = binding.moviesList
вот это тоже можно убрать из полей фрагмента, а именно здесь и работать с binding.moviesList 

(кстати, предлагаю именовать id у вьюх так чтобы было понятно за что они отвечают. Типо rvMovies вместо moviesList )

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +        })
это уберется , так как мы это проинициализируем в полях фрагмента

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +        recycler.addItemDecoration(MovieGridSpaceDecorator(space = resources.getDimensionPixelSize(
Кстати, вместо 
```
recycler = binding.moviesList
recycler.layoutManager = GridLayoutManager(requireContext(), 2)
        recycler.adapter = mainListAdapter
        recycler.addItemDecoration(
            MovieGridSpaceDecorator(
                space = resources.getDimensionPixelSize(
                    R.dimen.movie_grid_spacing
                )
            )
        )

```

Можно сделать так:

```
with(binding.moviesList) {
            layoutManager = GridLayoutManager(requireContext(), 2)
            adapter = mainListAdapter
            addItemDecoration(
                MovieGridSpaceDecorator(resources.getDimensionPixelSize(R.dimen.movie_grid_spacing))
            )
        }
```


Можешь почитать про эти штуки, они вроде называются scope functions - они очень удобные и упрощают код (Есть еще функции let, apply, run и also)

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +    }
вот это уберется, так как movieCardClickListener теперь lateinit

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +    }
это тоже уберется, потому что binding тоже теперь lateinit

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +            mainListAdapter.submitList(movieList.toMutableList())
вот это не очень хороший вариант , когда ты делаешь здесь  `movieList.toMutableList()`

Нужно прокидывать просто movieList

Я примерно догадываюсь, почему ты это сюда добавил, но чуть позже гляну, уже когда буду смотреть ViewModel

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +class MainListAdapter(
Ну, во-первых, мне кажется лучше его назвать типо 
MovieListAdapter

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +    private val movieCardClickListener: (Int) -> Unit,
Во вторых, лучше будет если у тебя лямбда будет не 

`private val movieCardClickListener: (Int) -> Unit,`
а 
`private val movieCardClickListener: (MovieData) -> Unit,`

Как никак, мы ведь кликаем не по какому то абстрактному айпишнику, а по фильму, и было бы логично что лямбда нам возвращала Movie, а не только его Id (или вообще какую-то рандомную цифру)

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +    private val onFavoriteClick: (Int, View) -> Unit,
здесь точно так же:

Клик происходит по лайку в фильме, а не по какой то цифре, так что лучше сделать, чтобы было 

`private val onFavoriteClick: (MovieData) -> Unit,`

Ну и да, вторым параметром можно убрать View - потому что он не нужен и нигде не используется

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +}
Вот это тоже можно полностью убрать, потому что изменением статуса Like должна заниматься ViewModel а не Adapter 
Адаптер тупо создает ViewHolder-ы и Биндит данные

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieItemDiffCallback.kt
> +    }
вот это можно будет убрать

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieItemDiffCallback.kt
> +    }
Вот это так-же можно будет убрать

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +    private val movieCardClickListener: (Int) -> Unit,
Здесь лучше как я уже ранее описал сделать вот так:

```
private val onFavoriteClick: (MovieData) -> Unit,
private val movieCardClickListener: (MovieData) -> Unit,
```

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +            reviewsCounter.text =
Можно поменять в строковых ресурсов  с 
`<string name="reviews_counter">%1$s reviews</string>`
на 
`<string name="reviews_counter">%1$d reviews</string>`

И тогда в getString можно будет просто прокинуть reviewsCount без .toString()

Потому что %1$d означает что сюда можно целое число вставить.

А вообще про форматирование можешь почитать, там еще есть другие типы форматирования через строковые ресурсы

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +                movieData.movieLengthMinutes.toString())
здесь точно так же как в предыдущем комменте, поменять чтобы ты прикидывал в getString число, а не строку

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +        }
1. Во первых , invoke - это operator function, поэтому ты можешь вместо  `movieCardClickListener.invoke(absoluteAdapterPosition)`
написать 
 `movieCardClickListener(absoluteAdapterPosition)`
2. Во вторых, в коллбеки прикидывай не позицию, а сам фильм

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +            R.color.white))
Этот код можно сделать красивее и понятнее:
```

val colorRes = if (liked) {
            R.color.like_color
        } else {
            R.color.white
        }
        
movieBinding.movieLike.setColorFilter(
    ContextCompat.getColor(movieBinding.root.context, colorRes)
)
```

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +    }
От этого метода можно избавиться, так как мы не будем снаружи у ViewHolder-а вызывать этот метод

Я там раньше вроде расписал

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +class MoviesViewModel(app: Application) : AndroidViewModel(app) {
чисто на будущее отмечу, что в будущем мы избавимся от AndroidViewModel
потому что она нужна только для контекста для loadMovies.

Просто когда будешь выпиливать это, не забудь переделать вьюмодель на обычную

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +            _moviesDataList.value = loadMovies(context = getApplication())
Мне кажется лучше использовать для MutableLiveData метод postValue , потому что можно с любого потока ставить, и не париться

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +    fun select(item: Int) {
здесь лучше чтобы было не 
`fun select(item: Int)`
а 
`fun select(item: MovieData)`

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +    fun changeFavouriteState(adapterIndex: Int) {
здесь тоже лучше работать сразу с фильмом, а не с его индексом

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +        }
плюс это можно не в корутинах запускать(как минимум пока что)

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +    private suspend fun fakeRequestChangeFavouriteState(adapterIndex: Int): List<MovieData>? {
ну и этот метод тоже пусть работает с MovieData, а не с индексом

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/ActorViewHolder.kt
> +}
Тут ок, но как вариант можно вот так рефакторнуть(но не обязательно):
```

 fun bindActor(actor: ActorData) {
        with(actorBinding) {
            actorName.text = actor.name

            Glide.with(root.context)
                .load(actor.imageUrl)
                .placeholder(R.drawable.ic_avatar_placeholder)
                .fallback(R.drawable.ic_avatar_placeholder)
                .into(actorPicture)
        }
    }
```

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/ActorsListAdapter.kt
> +class ActorsListAdapter : RecyclerView.Adapter<ActorViewHolder>() {
здесь тоже можешь кстати сделать ListAdapter, как с MovieListAdapter-ом

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/ActorsListAdapter.kt
> +class ActorsListAdapter : RecyclerView.Adapter<ActorViewHolder>() {
Либо можно не менять на листадаптер, но можно прокинуть в конструктор val actors

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    private val detailBinding get() = _detailBinding!!
Это поменять так же как я откомментил в FragmentMovieList

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    private lateinit var actorsListAdapter: ActorsListAdapter
Здесь тоже адаптер сразу проинициализировать

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    }
Так как ты тут ты решил через общую ViewModel делать, то этот код становится не нужным. 

Если хочешь, можем потом обсудить какими вообще способами можно это все сделать

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +        detailBinding.arrowBack.setOnClickListener { onBackPressed() }
Вот это вот можно тоже упросить, сделав у TextView с id backMarker параметр drawableStartCompat (или он как то так называется), тогда у тебя стрелка отобразится внутри самой TextView, и не будет 2 разных View, а только один, и это в итоге уберется

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +                requireContext().getString(R.string.plus_sign, movieData.pgAge.toString())
здесь тоже поменяй в ресурсах строк на d, чтобы можно было просто число прокинуть

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +                getString(R.string.reviews_counter, movieData.reviewsCount.toString())
здесь тоже поменяй в ресурсах строк на d, чтобы можно было просто число прокинуть

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +                requireContext().getString(R.string.plus_sign, movieData.pgAge.toString())
и внутри фрагмента можно обойтись без requireContext() а сразу вызвать метод getString

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +                requireContext().getString(R.string.storyline)
внутри фрагмента можно обойтись без requireContext() а сразу вызвать метод getString

А еще лучше такие строки, которые не изменяются , сразу в xml поставить (я там ранее коммент похожий оставлял)

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +                actorsListAdapter.actors = movieData.actorsList
вот этот список можно сразу в конструктор адаптера прикидывать, если мы его таким образом делаем, а если это будет ListAdapter, то через submitList

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +        actorsListAdapter = ActorsListAdapter()
вот это лучше проинициализировать в полях фрагмента

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +        val recycler: RecyclerView = detailBinding.actorsList
можно with(detailBinding.actorsList)

собственно я раньше похожий коммент оставлял

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    }
это можно убрать, потому что оно по умолчанию то же самое делает

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    }
это тоже уберется

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/utils/ActorsListSpaceDecorator.kt
> +class ActorsListSpaceDecorator(private val space: Int) : RecyclerView.ItemDecoration() {
есть еще идея - чтобы поменьше кода было,  внутри преобразовывать и высчитывать, то что ты делаешь перед тем как в конструктор кидаешь. Но тут как удобнее

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/utils/MovieCardClickListener.kt
> +}
1. Удали закомменченное
2. Лучше этот интерфейс держать не в Utils, где непонятно зачем он нужен и для чего, а внутри FragmentMovieList

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/utils/MovieGridSpaceDecorator.kt
> +class MovieGridSpaceDecorator(private val space: Int) : RecyclerView.ItemDecoration() {
точно так же можно спрятать преобразование и высчитывание dp внутрь, но это как удобно и не обязательно

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/utils/UsefullExtensions.kt
> +import android.content.res.Resources
Можно переименовать в что то более явное - типо DpExt, или DpConverterExt, чтобы когда их было много, было проще ориентироваться в них

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/drawable/detail_mask.xml
> +</vector>
Вместо этого можно использовать Shape 

```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:centerColor="@color/black_blue"
        android:endColor="@color/black_blue"
        android:angle="270"
        android:type="linear"
        android:centerX="0.9"/>
</shape>
```

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/drawable/item_rounded_rectangle_background.xml
> +-->
Комменты удали

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/drawable/item_rounded_rectangle_background.xml
> +        android:color="#FF636375" />
Цвета старайся держать в colors.xml

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/drawable/movie_mask.xml
> +</vector>
по сути такой же дровабл уже есть в detail_mask. Ну то есть как поменяешь его на shape, как я там предложил, то можно использовать его и там и там, а от дублирования избавиться

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/drawable/rg_rounded_background.xml
> +        android:color="#FF191926" />
цвета в colors.xml

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="match_parent"
Здесь можно поставить 0dp вместо Match_parent

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            app:layout_constraintBottom_toBottomOf="@+id/detail_guideline" />
Вот эти две вьюхи можешь отрефакторить вот так:

```
<androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/detail_backdrop"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:scaleType="centerCrop"
            tools:src="@tools:sample/backgrounds/scenic"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toTopOf="parent"
            app:layout_constraintBottom_toBottomOf="@+id/detail_guideline" />

        <androidx.appcompat.widget.AppCompatImageView
            android:id="@+id/detail_shadow"
            android:layout_width="0dp"
            android:layout_height="0dp"
            android:src="@drawable/detail_mask"
            android:scaleType="centerCrop"
            app:layout_constraintEnd_toEndOf="@id/detail_backdrop"
            app:layout_constraintStart_toStartOf="@id/detail_backdrop"
            app:layout_constraintTop_toTopOf="@id/detail_backdrop"
            app:layout_constraintBottom_toBottomOf="@id/detail_backdrop" />
```

Суть в том, что вторая вьюха у тебя полностью идет поверх первой, поэтому можно констрейнты расставить таким образом, чтобы она просто повторяла размеры за первой. 
Ну и да, лучше в ConstraintLayout-е пореже использовать Match_parent

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:fontFamily="@font/roboto_light"
```
  app:drawableStartCompat="@drawable/ic_arrow_back"
  android:drawablePadding="8dp"
```

Добавь эти две строчки, и тогда можно удалять верхний ImageView у которого id/arrow_back

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            app:layout_constraintTop_toTopOf="parent" />
Вот это можно удалить

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_marginStart="@dimen/size_2x"
кстати, большую часть вот этих marginStart можно убрать, если добавить два вертикальных гайдлайна с маргинами,а у вьюх псоставить констрейнты на эти гайдлайны

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_width="match_parent"
лучше 0dp вместо Match_parent

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_width="match_parent"
0dp

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_width="match_parent"
0dp

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:textColor="#FFECECEC"
этот цвет есть в Colors.xml можно сослаться на него, а не дублировать

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_width="match_parent"
0dp

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_width="match_parent"
0dp

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_width="match_parent"
0dp

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +        <androidx.appcompat.widget.AppCompatTextView
 Кстати,ты можешь не указывать явно AppCompatTextView и прочие AppCompat*** в xml, а просто писать TextView 

Потому что оно по идее подставляется и так само по себе

https://developer.android.com/reference/androidx/appcompat/widget/AppCompatTextView
_This will automatically be used when you use TextView in your layouts and the top-level activity / dialog is provided by appcompat. You should only need to manually use this class when writing custom views._

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +    <androidx.appcompat.widget.AppCompatImageView
Короче, думаю что можно убрать AppCompat*** из xml и просто использовать обычный нейминг

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:textSize="14sp"
Здесь можно тоже попробовать добавить startDrawableCompat , и тогда от ImageView которая выше можно будет избавиться

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/layout/view_holder_actor.xml
> +        style="@style/actor_cast"
LayoutWidth и LayoutHeight и вообще все что связано именно с размерами лучше не выносить в стили, а оставить в xml 

Потому что это может сбивать  

Плюс стили обычно именуются немного по другому

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/values/strings.xml
> +    <string name="minutes_counter">%1$s minutes</string>
Здесь везде можно поменять s на d, чтобы можно было в методе getString подставлять число

2021-01-10 01:16 UTC, Vladuken commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">4dp</item>
вот эти вещи лучше оставить в лейауте, а не в стилях

2021-01-10 06:53 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/data/ActorData.kt
> +@Parcelize
Убрал  @Parcelize и убрал "Data" (они и так пока в папке Data) живут.
@Parcelize -- следствие того, что раньше я в детальный фрагмент отдавал целиком объект "Movie", потом уже догнал что можно только индекс кидать.

2021-01-10 07:08 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/data/MovieMockedData.kt
> +package com.example.academyfundamentalsproject.data
Удалил, он уже не нужен

2021-01-10 07:20 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +    private lateinit var recycler: RecyclerView
Я что-то раньше делал с recycler вне initView(), потом собрал всё в кучу -- а "хвост" остался... Удалил )

2021-01-10 07:32 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +    private lateinit var mainListAdapter: MainListAdapter
Инициализацию вынес вверх, вполне логично. 
Ух ты, не знал что лямбдам можно так удобно имена давать -- сделал, читабельность кода выше.
И после этого initView() ещё немного переписал, действия с recycler-ом.

2021-01-10 07:35 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +    private val binding get() = _binding!!
Спасибо, писал "по-старому", по их же докам. Запомню новый подход.  )

2021-01-10 07:38 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +        binding.moviesListHeader.text = getString(R.string.movies_list)
А это точно никогда не будет меняться и не будет переиспользоваться для какого-то ещё экрана? Ок, убрал обратно в xml, если что -- никогда не сложно вернуть обратно.

2021-01-10 07:43 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +        recycler = binding.moviesList
Ох... На двух разных проектах меня "били по рукам" за противоположные вещи -- "зачем сокращать, когда недолго полностью написать" и "зачем писать длинное recyclerView когда это все равно список" ;-))

Пока утвержденного CodeStyle нету, нейминг оставлю +/- как есть, ок? )

2021-01-10 07:44 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +        recycler.addItemDecoration(MovieGridSpaceDecorator(space = resources.getDimensionPixelSize(
Я сделал через apply {}

2021-01-10 07:46 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +            mainListAdapter.submitList(movieList.toMutableList())
Да, у этого безобразия "ноги растут" из ViewModel, и здесь это уже не нужно, забыл убрать когда решал проблему с обновлением списка.

2021-01-10 09:29 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +}
val newLikeState = o.getBoolean(key) тут правда лишнее, надо лишь текущее состояние лайка получить и отобразить его в карточке ("тупо биндит данные" ;-) ). Убрал вовнутрь bindOnlyFavourite.

А остальное нужно, оно касается отображения изменения части информации на карточке. В MovieItemDiffCallback проверяется, если фильм тот же, но его контент другой прилетел -- смотрим что именно поменялось (поменяться пока может только лайк) -- пихаем в Bundle и потом адаптер смотрит, есть ли что там и отображает новое состояние, если есть. Как-то так :)

2021-01-10 09:53 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +    private val movieCardClickListener: (Int) -> Unit,
Вот тут не уверен на 100%... 
Так и было у меня сначала, (MovieData) вместо (Int).
Я ещё не сделал полностью домашку по Networking-у, но в обсуждении рабочего API (тут пока могу ошибаться) читал, что какая-то детальная информация по фильму доступна по дополнительному запросу (и у меня на одном проекте так было -- основной список отдельно, деталка -- по ID новости). Я попозже к этому ещё вернусь, но пока кажется что для деталки информации по фильму будет не достаточно, и нужно будет организовывать дополнительный запрос.

Так или иначе, вместо индекса адаптера сейчас возвращаю ID фильма, и по нему уже будет вытаскиваться остальная инфа. Ок?

2021-01-10 09:54 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +    private val onFavoriteClick: (Int, View) -> Unit,
View убрал как ненужное, прокидываю ID фильма.

2021-01-10 09:54 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieItemDiffCallback.kt
> +    }
Не-а )

2021-01-10 09:55 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +    private val movieCardClickListener: (Int) -> Unit,
Поменял аналогично тому что ранее было.

2021-01-10 10:01 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +            reviewsCounter.text =
ОК, поправил. У меня на каком-то этапе туда прилетала строка, а когда формат данных поменялся -- забыл поменять, да...

2021-01-10 10:08 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +            R.color.white))
Спасибо, не додумался до такого пока )

2021-01-10 10:08 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +    }
Будем )

2021-01-10 10:09 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +class MoviesViewModel(app: Application) : AndroidViewModel(app) {
Ой, да. Голову ломал как убрать контекст, потом решил что городить огород не буду, всё равно потом будет другой метод, а там и другое решение, без контекста. Надеюсь что не забуду.

2021-01-10 10:12 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +            _moviesDataList.value = loadMovies(context = getApplication())
А можно по умолчанию везде использовать  postValue  вместо value = ... ???

2021-01-10 10:13 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +    fun select(item: Int) {
Пока на ID-шнике остановился. Возможно, чуть позже переделаю.

2021-01-10 10:13 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +        }
Ок. Но это так, на будущее, чтобы не забыть... )

2021-01-10 10:14 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +    fun changeFavouriteState(adapterIndex: Int) {
Тут был индекс адаптера, сейчас (временно?) индекс фильма.

2021-01-10 10:25 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/ActorsListAdapter.kt
> +class ActorsListAdapter : RecyclerView.Adapter<ActorViewHolder>() {
И точно, тут же не будет ничего меняться, то что пришло то и показывается. Вряд ли будет список из 100 актёров с какой-нибудь подгрузкой с педжингом... 
ListAdapter -- наверное, перебор, он хорош когда diff какой-нибудь обсчитать в другом потоке.

2021-01-10 10:35 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    }
Убрал, да. Забыл.... ;(  
Способов наверняка много.
Я, например, при использовании Navigation Component использовал Safe Args для передачи параметров между фрагментами.

2021-01-10 10:42 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +        detailBinding.arrowBack.setOnClickListener { onBackPressed() }
Точно, спасибо! Забыл что такая штука есть, прикрутил.

2021-01-10 10:51 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    }
А как клик на стрелке назад и надписи "Back" иначе обрабатывать? Можно, конечно, это в лямбду перенести. Но мне кажется так нагляднее будет.

2021-01-10 10:56 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/utils/UsefullExtensions.kt
> +import android.content.res.Resources
Нейминг ... Вторая по частоте проблема в Андроиде ;-) На ходу не придумал подходящего названия, сейчас назвал иначе.

2021-01-10 11:02 UTC, AleksVira commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:fontFamily="@font/roboto_light"
А в чём разница с android:drawableStart=... ?

2021-01-10 11:32 UTC, AleksVira commented on app/src/main/res/drawable/detail_mask.xml
> +</vector>
А как у тебя получилось определить что centerX="0.9" ?
Я фактически только из-за этого взял из Фигмы вектор, так как с градиентом визуально получается не совсем так как в дизайне. ;(

2021-01-10 11:35 UTC, AleksVira commented on app/src/main/res/drawable/movie_mask.xml
> +</vector>
Пробовал сам тоже, и градиент пробовал с разными параметрами -- визуально получается не то. У меня с предложенным вариантом картинки слишком тёмные выходят.

2021-01-10 11:43 UTC, AleksVira commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_marginStart="@dimen/size_2x"
Согласен, что одно и то же можно сделать разными способами. С одной стороны два дополнительных объекта на Constraint-е появляются, с другой стороны для всех сразу проще границы настраивать... Неоднозначно. ;)

2021-01-10 14:44 UTC, AleksVira commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_width="match_parent"
Ну тоже вот не всегда однозначно. Конкретно в этом случае получается что вместо одной строки 
  android:layout_width="match_parent"
я должен написать две:
  android:layout_width="0dp"
  app:layout_constraintEnd_toEndOf="parent"

"По стилю" может и лучше, хотя фактически одно и то же.

2021-01-10 14:51 UTC, AleksVira commented on app/src/main/res/layout/fragment_movie_details.xml
> +        <androidx.appcompat.widget.AppCompatTextView
О, спасибо за наводку, а то я на работе на текущем проекте запарился AppCompatTextView вместо TextView и AppCompatImageView вместо ImageView в xml-ках переписывать, ибо такое пожелание лида! ;-)

2021-01-10 14:59 UTC, AleksVira commented on app/src/main/res/layout/fragment_movies_list.xml
> +    <androidx.appcompat.widget.AppCompatImageView
А вот с AppCompatImageView не так всё однозначно, ибо ImageView начинает требовать (видно как выделяется в XML) чтобы был указан contentDescription. Размечать их по всем файлам? .... Ну может быть чуть попозже...

2021-01-10 15:01 UTC, AleksVira commented on app/src/main/res/layout/fragment_movies_list.xml
> +        android:textSize="14sp"
ОК, сделал.

2021-01-10 15:33 UTC, AleksVira commented on app/src/main/res/layout/view_holder_actor.xml
> +        style="@style/actor_cast"
Не подумав, скопировал из того варианта вёрстки, когда это было фрагментом из 4-х картинок с подписями. Сейчас это один элемент, тащить что-то в стили тут без смысла. Поправил.

2021-01-10 15:36 UTC, AleksVira commented on app/src/main/res/values/styles.xml
> +        <item name="android:layout_marginTop">4dp</item>
Вообще убрал за ненадобностью.

2021-01-10 16:04 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +            _moviesDataList.value = loadMovies(context = getApplication())
Я обычно забиваю и везде postValue использую

2021-01-10 21:12 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +        recycler = binding.moviesList
Формально кодстайл - это то что ты утверждаешь (особенно когда проект полностью твой)

Можешь пока оставить, но то что я описал это просто один из вариантов того как можно именовать
Можешь погуглить и найти какой-нибудь удобный для себя (ну то есть я для себя обычно выбираю префикс_зачтоотвечает, типо rvMovies,или tvMovieTitle, или ivMovieLogo)

2021-01-11 00:04 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +    private val movieCardClickListener: (Int) -> Unit,
Предлагаю это обсудить завтра и проговорить словами как можно обойти ситуацию, которую ты описал

2021-01-11 00:14 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +}
Так, я в итоге понял для чего это нужно, так что все ок - убирать не нужно

Единственное предложил бы это немного рефакторнуть , чтобы стало вот так(или около):

```
 override fun onBindViewHolder(
        holder: MovieViewHolder,
        position: Int,
        payloads: MutableList<Any>,
    ) {
        if (payloads.isNotEmpty()) {
            val bundle = payloads[0] as Bundle
            for (key in bundle.keySet()) {
                if (key == LIKE) {
                    holder.bindOnlyFavourite(bundle.getBoolean(key))
                }
            }
        }

        super.onBindViewHolder(holder, position, payloads)
    }
```

ну или как то так

2021-01-11 00:15 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieItemDiffCallback.kt
> +    }
тогда предлагаю назвать типо TAG_LIKE или PAYLOAD_LIKE или PAYLOAD_TAG_LIKE, чтобы было понятно из названия для чего это нужно

2021-01-11 00:16 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieItemDiffCallback.kt
> +    }
Ладно, понял, что это убирать нельзя, так что предложения по небольшому рефактору:

вместо проверки diff.size() == 0 просто использовать diff.isEmpty

2021-01-11 00:17 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieViewHolder.kt
> +    private val movieCardClickListener: (Int) -> Unit,
Это тоже предлагаю обсудить голосом завтра, попробую явно донести идею

2021-01-11 00:18 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MoviesViewModel.kt
> +    fun select(item: Int) {
Это тоже проговорим

2021-01-11 00:22 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    private lateinit var actorsListAdapter: ActorsListAdapter
Думаю раз у нас список не изменяется извне, и мы кидаем адаптер сразу  с данными, можно убрать его из полей класса, и просто на месте инициализировать

2021-01-11 00:24 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    }
Можно просто вызвать activity?.onBackPressed() без доп метода 

(но вообще я слышал про еще один способ, но я с ним не работал - 
https://medium.com/better-programming/a-new-way-to-handle-back-press-in-fragments-8a67cdcda75e
 )

2021-01-11 00:25 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/utils/MovieCardClickListener.kt
> +}
Все еще считаю что лучше это не хранить отдельным файлом, а держать как внутренний класс , но это обсудим

2021-01-11 00:26 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/utils/UsefullExtensions.kt
> +import android.content.res.Resources
Кстати, заметил что это в итоге и не используется, мб удалить или начать использовать этот код?

2021-01-11 00:27 UTC, Vladuken commented on app/src/main/res/drawable/detail_mask.xml
> +</vector>
Я честно говоря не помню уже почему тут 0.9, скопировал из другого проекта. Думаю можно эту строчку удалить

Но кажется изначально это тоже из фигмы достал(либо руками сам поменял тот файл)

2021-01-11 00:27 UTC, Vladuken commented on app/src/main/res/drawable/movie_mask.xml
> +</vector>
А, если цвета различаются, то да, думаю можно оставить их два

2021-01-11 00:29 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:fontFamily="@font/roboto_light"
Обычно оно кидает ворнинги если просто drawableStart использовать

Здесь подробнее в первом ответе расписано
https://stackoverflow.com/questions/63479754/getting-appdrawableendcompat-instead-of-androiddrawableend-warning-for-lollipo/63481515

2021-01-11 00:31 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_marginStart="@dimen/size_2x"
Эти два объекта вообще никак не повлияют ни на что и иногда не стоит прям прыгать в  микрооптимизации, особенно там где это ни на что не влияет

Поэтому именно в таком случае лучше сделать себе удобнее да и код в целом красивее, чем усложнять себе жизнь

2021-01-11 00:34 UTC, Vladuken commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_width="match_parent"
matchParent и 0dp это разные вещи, и если уж используешь constraintLayout, то как мне кажется, нужно по его правилам работать - а именно через констрейнты 


+ это одно и то же только в случае если у нас констрейнты расставлены к parent, и то даже с таким способом иногда это не одно и то же (точно не помню, но если ты укажешь widthPercent(или как то так оно называется) то с matchParent мне кажется оно не отработает - и таких вещей много )

2021-01-11 00:36 UTC, Vladuken commented on app/src/main/res/layout/fragment_movies_list.xml
> +    <androidx.appcompat.widget.AppCompatImageView
Если ты не дашь contentDescription - то это будет лишь warning - на работу приложения это никак не скажется

Но вообще contentDescription нужен для слабовидящих и незрячих, и ты уже сам решаешь, будет ли твое приложение это поддерживать или нет. 

Так что как мне кажется в этом случае лучше с ворнингом, даже если решишь не провайдить contentDescription, чем без ворнинга (при том что контент дескрипшона не будет ни в первом ни во втором случае, но в случае без AppCompat, тебе Android Studio будет хотя бы напоминать о том что это можно добавить)

2021-01-11 18:53 UTC, Vladuken commented on app/src/main/res/drawable/detail_mask.xml
> +</vector>
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="rectangle">
    <gradient
        android:angle="270"
        android:endColor="#FF191926"
        android:startColor="#02191926"
        android:type="linear" />
</shape>

```

2021-01-17 10:25 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/FragmentMoviesList.kt
> +        recycler = binding.moviesList
Сделал рефакторинг имён

2021-01-17 10:36 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MainListAdapter.kt
> +    private val movieCardClickListener: (Int) -> Unit,
ОК, изменил отдаваемые данные

2021-01-17 10:39 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    private lateinit var actorsListAdapter: ActorsListAdapter
Там не всё так просто, если данных для списка актёров нет -- я вовсе не инициализирую адаптер.

2021-01-17 12:06 UTC, AleksVira commented on app/src/main/java/com/example/academyfundamentalsproject/utils/UsefullExtensions.kt
> +import android.content.res.Resources
Пока удалил.

2021-01-17 12:08 UTC, AleksVira commented on app/src/main/res/drawable/detail_mask.xml
> +</vector>
Поигрался ещё, не нравится результат через простой градиент. Может быть в группе увижу какое-то другое решение, н пока думаю оставить два экспортированных градиента. Они точно делают то, что дизайнер хотел.

2021-01-17 12:29 UTC, AleksVira commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:fontFamily="@font/roboto_light"
Заменил на простые ImageView и первый раз в жизни для таких штук прописал description )

2021-01-17 16:58 UTC, AleksVira commented on app/src/main/res/layout/fragment_movie_details.xml
> +            android:layout_marginStart="@dimen/size_2x"
Сделал с двумя направляющими, примерно то на то и выходит )

2021-01-31 19:29 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/main_list/MovieListAdapter.kt
> +        } else {
лучше здесь все-таки проверить на payloads.isNotEmpty и не делать дополнительное ответвление

2021-01-31 19:31 UTC, Vladuken commented on app/src/main/java/com/example/academyfundamentalsproject/movie_detail/FragmentMoviesDetails.kt
> +    private lateinit var actorsListAdapter: ActorsListAdapter
Тогда возможно более логично будет его вообще не хранить в полях фрагмента

Либо сделать nullable - типо он может быть а может и не быть


ПОтому что lateinit подразумевает что мы проинициализируем - но чуть попозже
А nullable - что элемента может и не быть

2021-01-31 19:33 UTC, merged